### PR TITLE
Update the list of supported connectors

### PR DESCRIPTION
**Pull request by ziegenberg**
##### SUMMARY

Update the list of supported connectors (especially the links) in README.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

- README.md
- module_utils

### CODE REVIEW

**Comment by ziegenberg** [comment]
For a first try, I've gone with the current minimum version introduced in #163. So this would be:

- PyMySQL >= v0.7.10
- MySQLdb >= v1.2.5

**Comment by Andersson007** [comment]
@ziegenberg thanks for the PR!
```
"msg": ".... Exception message: module 'MySQLdb' has no attribute '__version__'"
```
Is there another way to get it?

**Comment by Andersson007** [comment]
BTW before pushing, you can run all the tests locally, see https://github.com/ansible/community-docs/blob/main/create_pr_quick_start_guide.rst . It's very simple. Needs only Docker installed.

**Comment by Andersson007** [comment]
and for this collection you should use just `--docker` option without specifying a distro. So it'll run in a default container. My command usually look like (you should be in `~/ansible_collection/community/mysql/`, the path is important, `mysql` is the cloned repo with changes, see the guide above):
```
ansible-test integration test_mysql_user --docker -vvv > ~/test.log
```

**Comment by Andersson007** [comment]
@ziegenberg if you find something unclear while reading the guide https://github.com/ansible/community-docs/blob/main/create_pr_quick_start_guide.rst. I'd be really happy if you share it (feel free to create an issue under https://github.com/ansible/community-docs).

**Comment by ziegenberg** [comment]
> @ziegenberg thanks for the PR!
> ```
> "msg": ".... Exception message: module 'MySQLdb' has no attribute '__version__'"
> ```
> Is there another way to get it?

Yeah, I know. What a bummer. But I haven't had enough time to looked into it further. It was a bit late the other day and I had no energy left to setup testing. So I thought let's see what ci will make of it. Looks like it wasn't too fond of my code. :)

I'll have to investigate into this issue and do some local debugging.

**Comment by Andersson007** [comment]
> But I haven't had enough time to looked into it further. It was a bit late the other day and I had no energy left to setup testing.

There's no rush:) The main thing is not to burn out:)

**Comment by markuman** [comment]
Maybe it MySQL-Python should be dropped and also replaced by mysqlclient like in https://github.com/ansible-collections/community.proxysql/commit/df5ede0077c40da0f850410fd6a0f9fe14dade1f  
plus rework error handling with `from ansible.module_utils.basic import missing_required_lib`

**Comment by Andersson007** [comment]
@ziegenberg @bmalynovytch @Jorge-Rodriguez what do you think of ^ ?

**Comment by Jorge-Rodriguez** [comment]
> @ziegenberg @bmalynovytch @Jorge-Rodriguez what do you think of ^ ?

I agree, but we shouldn't further to follow the usual procedure of warnings about the connector no longer being supported and so on

**Comment by Jorge-Rodriguez** [comment]
@ziegenberg PR #163 has been superseded by #246

**Review by Jorge-Rodriguez — CHANGES_REQUESTED** [review]
These changes should conform to the discussion in #141
Additionally, we should implement the replacement of Python-MySQLdb with mysqlclient, which will affect the whole collection.

At this point it'd be up to @ziegenberg whether he wants to implement that replacement here.

**Comment by ziegenberg** [comment]
Hi!
Sorry for the long absence. I'll try to come up with the necessary changes in the next two weeks if that's ok with you.

**Comment by Jorge-Rodriguez** [comment]
> Hi! Sorry for the long absence. I'll try to come up with the necessary changes in the next two weeks if that's ok with you.

Welcome back! And thank you for working on this.

**Comment by Andersson007** [comment]
@ziegenberg feel free to re-open the PR or create a new one if you still want to finish it, thanks!
